// Base de datos de los 100 casos oficiales de Logic-Play UPTT (Inspector Lógico)
// Generado automáticamente desde el Guion de Casos oficial.
const CASOS_LOGICA = [
  {
    "id": 1,
    "nivel": 1,
    "numero": 1,
    "enunciado": "El Núcleo \"Barbarita de la Torre\" está ubicado en el municipio Trujillo.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: hecho verificable, tiene valor de verdad.",
    "feedbackError": "Es una afirmación declarativa verificable; no es pregunta ni orden. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 2,
    "nivel": 1,
    "numero": 2,
    "enunciado": "¿Ya instalaste el software Logic-Play en tu teléfono?",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: las preguntas no tienen valor de verdad.",
    "feedbackError": "Es una pregunta (signo '¿?'); no puede ser V ni F. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 3,
    "nivel": 1,
    "numero": 3,
    "enunciado": "¡Corre, se va a caer la conexión del servidor!",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: exclamación de alarma.",
    "feedbackError": "Es una exclamación urgente, no una afirmación verificable. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 4,
    "nivel": 1,
    "numero": 4,
    "enunciado": "Todo número primo mayor que 2 es impar.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: afirmación matemática con valor de verdad definido.",
    "feedbackError": "Es una proposición matemática (resulta V); no es pregunta ni orden. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 5,
    "nivel": 1,
    "numero": 5,
    "enunciado": "Por favor, entregue la prueba diagnóstica antes de las 10:00 am.",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una orden.",
    "feedbackError": "Es una orden ('entregue'); las órdenes no tienen valor de verdad. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 6,
    "nivel": 1,
    "numero": 6,
    "enunciado": "Siete es un número par.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: es proposición, aunque resulte falsa.",
    "feedbackError": "Aunque el contenido es falso, sigue siendo calificable como F. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 7,
    "nivel": 1,
    "numero": 7,
    "enunciado": "¡Qué difícil está la lógica proposicional!",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: exclamación de opinión.",
    "feedbackError": "Es una exclamación emotiva, no una afirmación verificable. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 8,
    "nivel": 1,
    "numero": 8,
    "enunciado": "El lenguaje de programación Python fue creado por Guido van Rossum.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: hecho histórico verificable.",
    "feedbackError": "Es un hecho verificable con valor de verdad definido. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 9,
    "nivel": 1,
    "numero": 9,
    "enunciado": "¿Cuántos conectivos lógicos existen en el sistema propuesto?",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una pregunta.",
    "feedbackError": "Es una pregunta; no tiene valor de verdad. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 10,
    "nivel": 1,
    "numero": 10,
    "enunciado": "Ojalá el laboratorio tenga conexión estable hoy.",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: expresa un deseo.",
    "feedbackError": "Es un deseo ('ojalá'), no una afirmación fija. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 11,
    "nivel": 1,
    "numero": 11,
    "enunciado": "La UPTTMBI forma ingenieros en informática.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: hecho institucional verificable.",
    "feedbackError": "Es una afirmación declarativa verificable. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 12,
    "nivel": 1,
    "numero": 12,
    "enunciado": "Cierra la puerta del laboratorio al salir.",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una orden.",
    "feedbackError": "Es una orden directa; no tiene valor de verdad. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 13,
    "nivel": 1,
    "numero": 13,
    "enunciado": "El número de estudiantes reprobados en el diagnóstico fue treinta y dos.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: dato verificable.",
    "feedbackError": "Es un dato verificable contra el registro. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 14,
    "nivel": 1,
    "numero": 14,
    "enunciado": "¿Es válido este argumento?",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una pregunta.",
    "feedbackError": "Es una pregunta sobre validez, no una afirmación. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 15,
    "nivel": 1,
    "numero": 15,
    "enunciado": "Cero es un número natural.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: valor de verdad definido por convención.",
    "feedbackError": "Es una proposición matemática (convencionalmente V). Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 16,
    "nivel": 1,
    "numero": 16,
    "enunciado": "¡Excelente trabajo con la tabla de verdad!",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: exclamación de felicitación.",
    "feedbackError": "Es una exclamación, no una afirmación verificable. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 17,
    "nivel": 1,
    "numero": 17,
    "enunciado": "El reglamento del PNFI exige que los estudiantes aprueben Algorítmica.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: norma descrita como hecho institucional.",
    "feedbackError": "Describe una regla existente como hecho verificable, no una orden dirigida a ti. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 18,
    "nivel": 1,
    "numero": 18,
    "enunciado": "Explique con sus propias palabras qué es una tautología.",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una instrucción.",
    "feedbackError": "Es una instrucción ('explique'); no tiene valor de verdad. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 19,
    "nivel": 1,
    "numero": 19,
    "enunciado": "La disyunción exclusiva solo es verdadera cuando exactamente una de las proposiciones es verdadera.",
    "veredicto": "ADMITIR",
    "feedbackOk": "Correcto: definición técnica verificable.",
    "feedbackError": "Es una afirmación técnica verificable, no una pregunta. Debía ADMITIRSE.",
    "esProposicion": true,
    "accionCorrecta": "ADMITIR"
  },
  {
    "id": 20,
    "nivel": 1,
    "numero": 20,
    "enunciado": "¿Por qué el software debe funcionar sin conexión a internet?",
    "veredicto": "RECHAZAR",
    "feedbackOk": "Correcto: es una pregunta.",
    "feedbackError": "Es una pregunta; no tiene valor de verdad. Debía RECHAZARSE.",
    "esProposicion": false,
    "accionCorrecta": "RECHAZAR"
  },
  {
    "id": 21,
    "nivel": 2,
    "numero": 1,
    "enunciado": "El servidor está encendido y la red está activa.",
    "veredicto": "p: El servidor está encendido. q: La red está activa. (sin negación)",
    "feedbackOk": "¡Bien! Dos cláusulas unidas por 'y'.",
    "feedbackError": "Busca la palabra que conecta dos ideas completas: aquí es 'y' (conjunción).",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 22,
    "nivel": 2,
    "numero": 2,
    "enunciado": "El estudiante aprueba el diagnóstico o repite el nivel.",
    "veredicto": "p: El estudiante aprueba el diagnóstico. q: El estudiante repite el nivel.",
    "feedbackOk": "Correcto: conector 'o'.",
    "feedbackError": "El conector es 'o' (disyunción); separa en dos cláusulas completas.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 23,
    "nivel": 2,
    "numero": 3,
    "enunciado": "Si el dispositivo tiene batería, entonces el juego se ejecuta.",
    "veredicto": "p: El dispositivo tiene batería. q: El juego se ejecuta.",
    "feedbackOk": "Correcto: 'si…entonces'.",
    "feedbackError": "Busca 'si…entonces': separa antecedente y consecuente.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 24,
    "nivel": 2,
    "numero": 4,
    "enunciado": "El código no compila.",
    "veredicto": "p: El código compila. (negación explícita: ¬p)",
    "feedbackOk": "Correcto: detectaste la negación.",
    "feedbackError": "Hay una negación explícita ('no'); la variable base es 'El código compila', negada.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 25,
    "nivel": 2,
    "numero": 5,
    "enunciado": "No es cierto que el laboratorio tenga internet estable y el suministro eléctrico falle constantemente.",
    "veredicto": "p: El laboratorio tiene internet estable. q: El suministro eléctrico falla constantemente. (negación externa sobre toda la conjunción)",
    "feedbackOk": "Correcto: la negación afecta a todo.",
    "feedbackError": "'No es cierto que' niega la conjunción completa, no solo una parte.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 26,
    "nivel": 2,
    "numero": 6,
    "enunciado": "El estudiante usa el teléfono celular pero no se distrae en el aula.",
    "veredicto": "p: usa el teléfono celular. q: se distrae en el aula. (negación sobre q)",
    "feedbackOk": "Correcto: 'pero'='y', más negación.",
    "feedbackError": "'Pero' equivale a 'y'; además hay un 'no' que niega solo la segunda cláusula.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 27,
    "nivel": 2,
    "numero": 7,
    "enunciado": "Ni el profesor llegó a tiempo ni los estudiantes trajeron el material.",
    "veredicto": "p: el profesor llegó a tiempo. q: los estudiantes trajeron el material. (ambas negadas)",
    "feedbackOk": "Correcto: 'ni…ni' niega ambas.",
    "feedbackError": "'Ni…ni' es una negación doble: niega las dos cláusulas a la vez.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 28,
    "nivel": 2,
    "numero": 8,
    "enunciado": "El sistema valida la respuesta si y solo si la tabla de verdad es correcta.",
    "veredicto": "p: el sistema valida la respuesta. q: la tabla de verdad es correcta.",
    "feedbackOk": "Correcto: bicondicional.",
    "feedbackError": "La frase clave es 'si y solo si'; separa en dos cláusulas completas.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 29,
    "nivel": 2,
    "numero": 9,
    "enunciado": "Carlos programa en Java o en Kotlin, pero no en ambos.",
    "veredicto": "p: Carlos programa en Java. q: Carlos programa en Kotlin.",
    "feedbackOk": "Correcto: disyunción exclusiva.",
    "feedbackError": "'O…pero no ambos' indica que solo una cláusula puede ser verdadera.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 30,
    "nivel": 2,
    "numero": 10,
    "enunciado": "El estudiante obtiene la insignia siempre que complete el nivel.",
    "veredicto": "p: completa el nivel. q: obtiene la insignia.",
    "feedbackOk": "Correcto: 'siempre que'=condicional.",
    "feedbackError": "'Siempre que' equivale a 'si…entonces', con el orden invertido.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 31,
    "nivel": 2,
    "numero": 11,
    "enunciado": "El proyecto no fue aprobado por el jurado.",
    "veredicto": "p: El proyecto fue aprobado por el jurado. (negación explícita)",
    "feedbackOk": "Correcto.",
    "feedbackError": "Hay un 'no' explícito sobre una sola cláusula simple.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 32,
    "nivel": 2,
    "numero": 12,
    "enunciado": "El teléfono tiene señal y, además, el estudiante abre la aplicación o cierra la sesión.",
    "veredicto": "p: tiene señal. q: abre la aplicación. r: cierra la sesión.",
    "feedbackOk": "Correcto: 3 variables combinadas.",
    "feedbackError": "Hay tres cláusulas: una unida con 'y' a un grupo unido internamente con 'o'.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 33,
    "nivel": 2,
    "numero": 13,
    "enunciado": "Si el estudiante identifica correctamente las premisas y aísla las variables atómicas, entonces resuelve el ejercicio de segmentación.",
    "veredicto": "p: identifica las premisas. q: aísla las variables. r: resuelve el ejercicio.",
    "feedbackOk": "Correcto: antecedente compuesto.",
    "feedbackError": "El antecedente del 'si…entonces' tiene dos cláusulas unidas por 'y'.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 34,
    "nivel": 2,
    "numero": 14,
    "enunciado": "El estudiante pierde la evaluación solo si llega tarde.",
    "veredicto": "p: llega tarde. q: pierde la evaluación.",
    "feedbackOk": "Correcto: 'solo si'.",
    "feedbackError": "'Solo si' introduce el consecuente, no el antecedente; cuidado con el orden.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 35,
    "nivel": 2,
    "numero": 15,
    "enunciado": "Es falso que el estudiante haya asistido a clase y haya entregado la tarea.",
    "veredicto": "p: asistió a clase. q: entregó la tarea. (negación externa)",
    "feedbackOk": "Correcto: 'es falso que' niega todo.",
    "feedbackError": "'Es falso que' es otra forma de negación externa, igual que el caso 5.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 36,
    "nivel": 2,
    "numero": 16,
    "enunciado": "El laboratorio abre los lunes, los miércoles y los viernes.",
    "veredicto": "p: abre lunes. q: abre miércoles. r: abre viernes. (conjunción)",
    "feedbackOk": "Correcto: 3 variables, conjunción.",
    "feedbackError": "Cada día es una cláusula simple; todas unidas por 'y' (aunque se escriban con comas).",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 37,
    "nivel": 2,
    "numero": 17,
    "enunciado": "El estudiante gana la insignia dorada si y solo si no comete ningún error en el nivel.",
    "veredicto": "p: gana la insignia. q: comete algún error. (p↔¬q)",
    "feedbackOk": "Correcto: bicondicional con negación.",
    "feedbackError": "Hay un 'si y solo si' y además una negación ('no comete') dentro de una cláusula.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 38,
    "nivel": 2,
    "numero": 18,
    "enunciado": "Tampoco el docente ni el estudiante revisaron el manual antes del examen.",
    "veredicto": "p: el docente revisó el manual. q: el estudiante revisó el manual. (ambas negadas)",
    "feedbackOk": "Correcto.",
    "feedbackError": "'Tampoco… ni' es otra forma de negar ambas cláusulas a la vez.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 39,
    "nivel": 2,
    "numero": 19,
    "enunciado": "Tanto la abstracción como la segmentación son necesarias para aprobar el nivel uno.",
    "veredicto": "p: la abstracción es necesaria. q: la segmentación es necesaria. (conjunción)",
    "feedbackOk": "Correcto: 'tanto…como'=conjunción.",
    "feedbackError": "'Tanto…como' es una forma de decir 'y' (conjunción).",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 40,
    "nivel": 2,
    "numero": 20,
    "enunciado": "Si el estudiante no practica, entonces no mejora su rendimiento, y si no mejora su rendimiento, entonces no avanza de nivel.",
    "veredicto": "p: practica. q: mejora su rendimiento. r: avanza de nivel. (todas negadas)",
    "feedbackOk": "Correcto: cadena de condicionales.",
    "feedbackError": "Hay tres cláusulas negadas, encadenadas en dos condicionales unidos por 'y'.",
    "accionCorrecta": "CONFIRMAR"
  },
  {
    "id": 41,
    "nivel": 3,
    "numero": 1,
    "enunciado": "p: \"Hace calor\". Formaliza: \"No hace calor\".",
    "veredicto": "¬p",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Negación en la tabla de conectivos.",
    "formula": "¬p",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 42,
    "nivel": 3,
    "numero": 2,
    "enunciado": "p: servidor activo, q: red funciona. \"El servidor está activo y la red funciona\".",
    "veredicto": "p∧q",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Conjunción.",
    "formula": "p∧q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 43,
    "nivel": 3,
    "numero": 3,
    "enunciado": "\"El estudiante aprueba o repite\".",
    "veredicto": "p∨q",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Disyunción inclusiva.",
    "formula": "p∨q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 44,
    "nivel": 3,
    "numero": 4,
    "enunciado": "\"Juan estudia lógica o bases de datos, pero no ambas cosas a la vez\".",
    "veredicto": "p⊕q",
    "feedbackOk": "Correcto.",
    "feedbackError": "La frase 'pero no ambas' es la marca de Disyunción exclusiva.",
    "formula": "p⊕q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 45,
    "nivel": 3,
    "numero": 5,
    "enunciado": "\"Si el dispositivo tiene batería, entonces el juego se ejecuta\".",
    "veredicto": "p→q",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Condicional.",
    "formula": "p→q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 46,
    "nivel": 3,
    "numero": 6,
    "enunciado": "p: llueve, q: se cancela la práctica. \"Se cancela la práctica solo si llueve\".",
    "veredicto": "q→p",
    "feedbackOk": "Correcto: dirección invertida de 'solo si'.",
    "feedbackError": "'Solo si' invierte el orden habitual: aquí es q→p, no p→q. Revisa la nota de dirección.",
    "formula": "q→p",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 47,
    "nivel": 3,
    "numero": 7,
    "enunciado": "\"El estudiante mejora si practica\".",
    "veredicto": "p→q",
    "feedbackOk": "Correcto.",
    "feedbackError": "'Mejora si practica' equivale a 'si practica, entonces mejora'.",
    "formula": "p→q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 48,
    "nivel": 3,
    "numero": 8,
    "enunciado": "\"Puedes iniciar sesión si tienes usuario y contraseña\".",
    "veredicto": "(p∧q)→r",
    "feedbackOk": "Correcto: antecedente compuesto.",
    "feedbackError": "El antecedente combina dos condiciones con ∧ antes de aplicar →.",
    "formula": "(p∧q)→r",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 49,
    "nivel": 3,
    "numero": 9,
    "enunciado": "\"El triángulo es equilátero si y solo si tiene los tres ángulos iguales\".",
    "veredicto": "p↔q",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Bicondicional.",
    "formula": "p↔q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 50,
    "nivel": 3,
    "numero": 10,
    "enunciado": "\"Un número es par si y solo si es divisible por 2\".",
    "veredicto": "p↔q",
    "feedbackOk": "Correcto.",
    "feedbackError": "Revisa la fila de Bicondicional.",
    "formula": "p↔q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 51,
    "nivel": 3,
    "numero": 11,
    "enunciado": "\"El sistema aprueba la respuesta si y solo si la respuesta no contiene errores\".",
    "veredicto": "p↔¬q",
    "feedbackOk": "Correcto: bicondicional con negación.",
    "feedbackError": "El lado derecho del bicondicional lleva una negación: no olvides el ¬.",
    "formula": "p↔¬q",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 52,
    "nivel": 3,
    "numero": 12,
    "enunciado": "\"No es el caso que hoy sea lunes y feriado a la vez\".",
    "veredicto": "¬(p∧q)",
    "feedbackOk": "Correcto: equivalente a NAND.",
    "feedbackError": "Esta es la forma NAND (negación conjunta): niega toda la conjunción.",
    "formula": "¬(p∧q)",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 53,
    "nivel": 3,
    "numero": 13,
    "enunciado": "\"El estudiante no trae ni el teléfono ni la laptop\".",
    "veredicto": "¬(p∨q)",
    "feedbackOk": "Correcto: equivalente a NOR.",
    "feedbackError": "Esta es la forma NOR (negación alterna): niega toda la disyunción.",
    "formula": "¬(p∨q)",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 54,
    "nivel": 3,
    "numero": 14,
    "enunciado": "\"Si hay errores de sintaxis, el código no compila\".",
    "veredicto": "q→¬p",
    "feedbackOk": "Correcto.",
    "feedbackError": "El consecuente lleva la negación: q→¬p, no ¬p→q.",
    "formula": "q→¬p",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 55,
    "nivel": 3,
    "numero": 15,
    "enunciado": "\"Ana avanza de trayecto si y solo si aprueba tanto matemática como lógica\".",
    "veredicto": "r↔(p∧q)",
    "feedbackOk": "Correcto: bicondicional con antecedente conjuntivo.",
    "feedbackError": "El lado derecho del ↔ es una conjunción de dos variables.",
    "formula": "r↔(p∧q)",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 56,
    "nivel": 3,
    "numero": 16,
    "enunciado": "\"Si el servidor falla, entonces se activa el respaldo y el servicio continúa\".",
    "veredicto": "p→(q∧r)",
    "feedbackOk": "Correcto.",
    "feedbackError": "Todo lo que sigue a 'entonces' va agrupado dentro del paréntesis, unido por ∧.",
    "formula": "p→(q∧r)",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 57,
    "nivel": 3,
    "numero": 17,
    "enunciado": "\"El estudiante pierde la evaluación solo si llega tarde\".",
    "veredicto": "q→p",
    "feedbackOk": "Correcto.",
    "feedbackError": "Mismo caso que el ejercicio 6: 'solo si' invierte el orden.",
    "formula": "q→p",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 58,
    "nivel": 3,
    "numero": 18,
    "enunciado": "\"El estudiante avanza al nivel 4 si y solo si domina la conjunción y la disyunción\".",
    "veredicto": "r↔(p∧q)",
    "feedbackOk": "Correcto.",
    "feedbackError": "Bicondicional con antecedente conjuntivo, igual que el ejercicio 15.",
    "formula": "r↔(p∧q)",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 59,
    "nivel": 3,
    "numero": 19,
    "enunciado": "\"Si el argumento es válido y las premisas son verdaderas, entonces la conclusión es verdadera\".",
    "veredicto": "(p∧q)→r",
    "feedbackOk": "Correcto.",
    "feedbackError": "Antecedente compuesto por conjunción antes del →.",
    "formula": "(p∧q)→r",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 60,
    "nivel": 3,
    "numero": 20,
    "enunciado": "\"El dispositivo no recibe notificaciones si y solo si está en modo avión\".",
    "veredicto": "¬q↔p",
    "feedbackOk": "Correcto.",
    "feedbackError": "El lado izquierdo del ↔ lleva la negación: no lo olvides.",
    "formula": "¬q↔p",
    "accionCorrecta": "FORMALIZAR"
  },
  {
    "id": 61,
    "nivel": 4,
    "numero": 1,
    "enunciado": "p ∨ ¬p",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto: tercero excluido.",
    "feedbackError": "Revisa cada fila: p o ¬p siempre cubre el V.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 62,
    "nivel": 4,
    "numero": 2,
    "enunciado": "p ∧ ¬p",
    "veredicto": "Contradicción",
    "feedbackOk": "Correcto: no contradicción.",
    "feedbackError": "p y ¬p nunca pueden ser ambas verdaderas.",
    "tipo": "CONTRADICCION",
    "accionCorrecta": "CONTRADICCION"
  },
  {
    "id": 63,
    "nivel": 4,
    "numero": 3,
    "enunciado": "p → p",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto.",
    "feedbackError": "Un condicional con el mismo antecedente y consecuente es siempre V.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 64,
    "nivel": 4,
    "numero": 4,
    "enunciado": "p ↔ p",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto.",
    "feedbackError": "Toda proposición es equivalente a sí misma.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 65,
    "nivel": 4,
    "numero": 5,
    "enunciado": "p ∧ q",
    "veredicto": "Contingencia",
    "feedbackOk": "Correcto.",
    "feedbackError": "Solo es V cuando ambas son V; en las otras 3 filas es F: eso es Contingencia.",
    "tipo": "CONTINGENCIA",
    "accionCorrecta": "CONTINGENCIA"
  },
  {
    "id": 66,
    "nivel": 4,
    "numero": 6,
    "enunciado": "p ∨ q",
    "veredicto": "Contingencia",
    "feedbackOk": "Correcto.",
    "feedbackError": "Solo es F cuando ambas son F; en las otras filas es V: eso es Contingencia.",
    "tipo": "CONTINGENCIA",
    "accionCorrecta": "CONTINGENCIA"
  },
  {
    "id": 67,
    "nivel": 4,
    "numero": 7,
    "enunciado": "(p ∧ q) → p",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto: ley de Simplificación.",
    "feedbackError": "Si el antecedente es F, la condicional ya es V; si es V, el consecuente también.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 68,
    "nivel": 4,
    "numero": 8,
    "enunciado": "p → (p ∨ q)",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto: ley de Adición.",
    "feedbackError": "El consecuente (p∨q) siempre es V cuando p es V; si p es F, la condicional ya es V.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 69,
    "nivel": 4,
    "numero": 9,
    "enunciado": "(p → q) ↔ (¬p ∨ q)",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto: equivalencia material.",
    "feedbackError": "p→q y ¬p∨q son formas equivalentes; su bicondicional siempre da V.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 70,
    "nivel": 4,
    "numero": 10,
    "enunciado": "¬(p ∧ q) ↔ (¬p ∨ ¬q)",
    "veredicto": "Tautología (De Morgan)",
    "feedbackOk": "Correcto: 1ra ley de De Morgan.",
    "feedbackError": "Revisa la ley de De Morgan en la tabla de equivalencias.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 71,
    "nivel": 4,
    "numero": 11,
    "enunciado": "¬(p ∨ q) ↔ (¬p ∧ ¬q)",
    "veredicto": "Tautología (De Morgan)",
    "feedbackOk": "Correcto: 2da ley de De Morgan.",
    "feedbackError": "Revisa la ley de De Morgan en la tabla de equivalencias.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 72,
    "nivel": 4,
    "numero": 12,
    "enunciado": "(p → q) ∧ p ∧ ¬q",
    "veredicto": "Contradicción",
    "feedbackOk": "Correcto: niega el Modus Ponens.",
    "feedbackError": "Si p es V y q es F, p→q ya es F; la conjunción completa nunca puede ser V.",
    "tipo": "CONTRADICCION",
    "accionCorrecta": "CONTRADICCION"
  },
  {
    "id": 73,
    "nivel": 4,
    "numero": 13,
    "enunciado": "p ⊕ p",
    "veredicto": "Contradicción",
    "feedbackOk": "Correcto.",
    "feedbackError": "Una proposición nunca es 'exclusivamente distinta' de sí misma: siempre F.",
    "tipo": "CONTRADICCION",
    "accionCorrecta": "CONTRADICCION"
  },
  {
    "id": 74,
    "nivel": 4,
    "numero": 14,
    "enunciado": "p ↔ ¬p",
    "veredicto": "Contradicción",
    "feedbackOk": "Correcto.",
    "feedbackError": "p nunca puede tener el mismo valor que su propia negación.",
    "tipo": "CONTRADICCION",
    "accionCorrecta": "CONTRADICCION"
  },
  {
    "id": 75,
    "nivel": 4,
    "numero": 15,
    "enunciado": "(p ∧ q) ∨ (¬p ∧ ¬q)",
    "veredicto": "Contingencia",
    "feedbackOk": "Correcto: equivale a p↔q.",
    "feedbackError": "Es V cuando p y q coinciden (ambas V o ambas F) y F cuando difieren.",
    "tipo": "CONTINGENCIA",
    "accionCorrecta": "CONTINGENCIA"
  },
  {
    "id": 76,
    "nivel": 4,
    "numero": 16,
    "enunciado": "(p → q) ∨ (q → p)",
    "veredicto": "Tautología",
    "feedbackOk": "Correcto.",
    "feedbackError": "En cualquier combinación, al menos uno de los dos condicionales resulta V.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 77,
    "nivel": 4,
    "numero": 17,
    "enunciado": "(p ∧ (p → q)) → q",
    "veredicto": "Tautología (Modus Ponens)",
    "feedbackOk": "Correcto: forma tautológica del Modus Ponens.",
    "feedbackError": "Construye la tabla completa: nunca hay fila con antecedente V y consecuente F.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 78,
    "nivel": 4,
    "numero": 18,
    "enunciado": "((p → q) ∧ ¬q) → ¬p",
    "veredicto": "Tautología (Modus Tollens)",
    "feedbackOk": "Correcto: forma tautológica del Modus Tollens.",
    "feedbackError": "Construye la tabla completa: nunca hay fila con antecedente V y consecuente F.",
    "tipo": "TAUTOLOGIA",
    "accionCorrecta": "TAUTOLOGIA"
  },
  {
    "id": 79,
    "nivel": 4,
    "numero": 19,
    "enunciado": "(p → q) ∧ (q → r) ∧ p ∧ ¬r",
    "veredicto": "Contradicción",
    "feedbackOk": "Correcto: niega el Silogismo Hipotético.",
    "feedbackError": "Si p→q, q→r y p son V, r debe ser V; pedir ¬r a la vez es imposible.",
    "tipo": "CONTRADICCION",
    "accionCorrecta": "CONTRADICCION"
  },
  {
    "id": 80,
    "nivel": 4,
    "numero": 20,
    "enunciado": "(p ∧ q) ∨ (¬p ∧ r) ∨ (¬q ∧ ¬r)",
    "veredicto": "Contingencia",
    "feedbackOk": "Correcto.",
    "feedbackError": "Construye las 8 filas con p,q,r: encontrarás tanto V como F en el resultado.",
    "tipo": "CONTINGENCIA",
    "accionCorrecta": "CONTINGENCIA"
  },
  {
    "id": 81,
    "nivel": 5,
    "numero": 1,
    "enunciado": "\"Si estudio, entonces apruebo.\" \"Estudio.\" ∴ \"Apruebo.\"",
    "veredicto": "VÁLIDO — Modus Ponens",
    "feedbackOk": "Correcto: identificaste Modus Ponens.",
    "feedbackError": "Esquema p→q, p ⊢ q: es exactamente Modus Ponens, un patrón válido.",
    "esValido": true,
    "reglaOFalacia": "Modus Ponens",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 82,
    "nivel": 5,
    "numero": 2,
    "enunciado": "\"Si llueve, se moja la calle.\" \"No se moja la calle.\" ∴ \"No llueve.\"",
    "veredicto": "VÁLIDO — Modus Tollens",
    "feedbackOk": "Correcto: Modus Tollens.",
    "feedbackError": "Esquema p→q, ¬q ⊢ ¬p: es Modus Tollens, válido.",
    "esValido": true,
    "reglaOFalacia": "Modus Tollens",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 83,
    "nivel": 5,
    "numero": 3,
    "enunciado": "\"Si el servidor falla, se activa el respaldo.\" \"Se activa el respaldo.\" ∴ \"El servidor falla.\"",
    "veredicto": "INVÁLIDO — Afirmación del consecuente",
    "feedbackOk": "Correcto: detectaste la falacia.",
    "feedbackError": "De p→q y q no puede concluirse p; puede haber otra causa para que se active el respaldo.",
    "esValido": false,
    "reglaOFalacia": "Afirmación del consecuente",
    "accionCorrecta": "INVALIDO"
  },
  {
    "id": 84,
    "nivel": 5,
    "numero": 4,
    "enunciado": "\"Si trabajo duro, tengo éxito.\" \"No trabajo duro.\" ∴ \"No tengo éxito.\"",
    "veredicto": "INVÁLIDO — Negación del antecedente",
    "feedbackOk": "Correcto: detectaste la falacia.",
    "feedbackError": "De p→q y ¬p no puede concluirse ¬q; puede haber otro camino al éxito.",
    "esValido": false,
    "reglaOFalacia": "Negación del antecedente",
    "accionCorrecta": "INVALIDO"
  },
  {
    "id": 85,
    "nivel": 5,
    "numero": 5,
    "enunciado": "\"Si p entonces q.\" \"Si q entonces r.\" ∴ \"Si p entonces r.\"",
    "veredicto": "VÁLIDO — Silogismo Hipotético",
    "feedbackOk": "Correcto.",
    "feedbackError": "p→q y q→r encadenan directamente a p→r.",
    "esValido": true,
    "reglaOFalacia": "Silogismo Hipotético",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 86,
    "nivel": 5,
    "numero": 6,
    "enunciado": "\"El estudiante aprueba o repite.\" \"El estudiante no aprueba.\" ∴ \"El estudiante repite.\"",
    "veredicto": "VÁLIDO — Silogismo Disyuntivo",
    "feedbackOk": "Correcto.",
    "feedbackError": "De p∨q y ¬p se sigue q necesariamente.",
    "esValido": true,
    "reglaOFalacia": "Silogismo Disyuntivo",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 87,
    "nivel": 5,
    "numero": 7,
    "enunciado": "\"Juan estudia lógica y bases de datos.\" ∴ \"Juan estudia lógica.\"",
    "veredicto": "VÁLIDO — Simplificación",
    "feedbackOk": "Correcto.",
    "feedbackError": "De una conjunción p∧q siempre puede extraerse p por sí sola.",
    "esValido": true,
    "reglaOFalacia": "Simplificación",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 88,
    "nivel": 5,
    "numero": 8,
    "enunciado": "\"El código compila.\" \"No hay errores de sintaxis.\" ∴ \"El código compila y no hay errores de sintaxis.\"",
    "veredicto": "VÁLIDO — Conjunción",
    "feedbackOk": "Correcto.",
    "feedbackError": "Dos verdades por separado pueden unirse siempre en una conjunción.",
    "esValido": true,
    "reglaOFalacia": "Conjunción",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 89,
    "nivel": 5,
    "numero": 9,
    "enunciado": "\"Ana aprobó el examen.\" ∴ \"Ana aprobó el examen o ganó una beca.\"",
    "veredicto": "VÁLIDO — Adición",
    "feedbackOk": "Correcto.",
    "feedbackError": "Una proposición verdadera puede añadirse a cualquier disyunción sin perder validez.",
    "esValido": true,
    "reglaOFalacia": "Adición",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 90,
    "nivel": 5,
    "numero": 10,
    "enunciado": "\"Si estudio, apruebo.\" \"Si duermo bien, rindo mejor.\" \"Estudio o duermo bien.\" ∴ \"Apruebo o rindo mejor.\"",
    "veredicto": "VÁLIDO — Dilema Constructivo",
    "feedbackOk": "Correcto.",
    "feedbackError": "Con dos condicionales y la disyunción de sus antecedentes, se sigue la disyunción de sus consecuentes.",
    "esValido": true,
    "reglaOFalacia": "Dilema Constructivo",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 91,
    "nivel": 5,
    "numero": 11,
    "enunciado": "\"Si el dispositivo tiene batería, el juego se ejecuta.\" \"El juego no se ejecuta.\" ∴ \"El dispositivo no tiene batería.\"",
    "veredicto": "VÁLIDO — Modus Tollens",
    "feedbackOk": "Correcto.",
    "feedbackError": "p→q, ¬q ⊢ ¬p es Modus Tollens; aquí q='el juego se ejecuta'.",
    "esValido": true,
    "reglaOFalacia": "Modus Tollens",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 92,
    "nivel": 5,
    "numero": 12,
    "enunciado": "\"El estudiante gana la insignia o pasa de nivel.\" \"El estudiante gana la insignia.\" ∴ \"El estudiante no pasa de nivel.\"",
    "veredicto": "INVÁLIDO — Uso indebido de disyunción inclusiva",
    "feedbackOk": "Correcto: detectaste el error.",
    "feedbackError": "p∨q no excluye que ambas sean verdaderas; afirmar p no permite negar q.",
    "esValido": false,
    "reglaOFalacia": "Uso indebido de disyunción inclusiva",
    "accionCorrecta": "INVALIDO"
  },
  {
    "id": 93,
    "nivel": 5,
    "numero": 13,
    "enunciado": "\"Si p entonces q.\" \"Si r entonces s.\" \"p o r.\" ∴ \"q o s.\"",
    "veredicto": "VÁLIDO — Dilema Constructivo",
    "feedbackOk": "Correcto.",
    "feedbackError": "Mismo esquema que el ejercicio 10, con variables distintas.",
    "esValido": true,
    "reglaOFalacia": "Dilema Constructivo",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 94,
    "nivel": 5,
    "numero": 14,
    "enunciado": "\"No es cierto que llueva y haga sol.\" \"Llueve.\" ∴ \"No hace sol.\"",
    "veredicto": "VÁLIDO — De Morgan + Silogismo Disyuntivo",
    "feedbackOk": "Correcto.",
    "feedbackError": "¬(p∧q) equivale a ¬p∨¬q; si p es V, ¬p es F, así que ¬q debe ser V.",
    "esValido": true,
    "reglaOFalacia": "De Morgan + Silogismo Disyuntivo",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 95,
    "nivel": 5,
    "numero": 15,
    "enunciado": "\"El sistema valida la respuesta si y solo si no hay errores.\" \"Hay errores.\" ∴ \"El sistema no valida la respuesta.\"",
    "veredicto": "VÁLIDO — Aplicación del bicondicional",
    "feedbackOk": "Correcto.",
    "feedbackError": "En p↔¬q, si q es V entonces ¬q es F, y por el bicondicional p también debe ser F.",
    "esValido": true,
    "reglaOFalacia": "Aplicación del bicondicional",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 96,
    "nivel": 5,
    "numero": 16,
    "enunciado": "\"Si apruebo lógica, avanzo de trayecto.\" \"Avanzo de trayecto.\" ∴ \"Apruebo lógica.\"",
    "veredicto": "INVÁLIDO — Afirmación del consecuente",
    "feedbackOk": "Correcto: detectaste la falacia.",
    "feedbackError": "De p→q y q no puede concluirse p: pudo avanzar de trayecto por otra razón.",
    "esValido": false,
    "reglaOFalacia": "Afirmación del consecuente",
    "accionCorrecta": "INVALIDO"
  },
  {
    "id": 97,
    "nivel": 5,
    "numero": 17,
    "enunciado": "\"El estudiante practica todos los días o no mejora.\" \"El estudiante mejora.\" ∴ \"El estudiante practica todos los días.\"",
    "veredicto": "VÁLIDO — Silogismo Disyuntivo",
    "feedbackOk": "Correcto.",
    "feedbackError": "La premisa equivale a p∨¬q; si q (mejora) es V, ¬q es F, así que p debe ser V.",
    "esValido": true,
    "reglaOFalacia": "Silogismo Disyuntivo",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 98,
    "nivel": 5,
    "numero": 18,
    "enunciado": "\"Si el manual está actualizado, los docentes lo consultan.\" \"Los docentes no consultan el manual.\" ∴ \"El manual no está actualizado.\"",
    "veredicto": "VÁLIDO — Modus Tollens",
    "feedbackOk": "Correcto.",
    "feedbackError": "p→q, ¬q ⊢ ¬p, con q='los docentes consultan el manual'.",
    "esValido": true,
    "reglaOFalacia": "Modus Tollens",
    "accionCorrecta": "VALIDO"
  },
  {
    "id": 99,
    "nivel": 5,
    "numero": 19,
    "enunciado": "\"El proyecto es aprobado por el jurado o se solicita una revisión.\" \"Se solicita una revisión.\" ∴ \"El proyecto no es aprobado por el jurado.\"",
    "veredicto": "INVÁLIDO — Uso indebido de disyunción inclusiva",
    "feedbackOk": "Correcto: detectaste el error.",
    "feedbackError": "p∨q no excluye que ambas ocurran; afirmar q no permite negar p.",
    "esValido": false,
    "reglaOFalacia": "Uso indebido de disyunción inclusiva",
    "accionCorrecta": "INVALIDO"
  },
  {
    "id": 100,
    "nivel": 5,
    "numero": 20,
    "enunciado": "\"Si domina la abstracción, domina la segmentación.\" \"Si domina la segmentación, domina la formalización.\" \"Domina la abstracción.\" ∴ \"Domina la formalización.\"",
    "veredicto": "VÁLIDO — Silogismo Hipotético (doble) + Modus Ponens",
    "feedbackOk": "Correcto.",
    "feedbackError": "Encadena los dos condicionales y aplica luego el dato de que domina la abstracción.",
    "esValido": true,
    "reglaOFalacia": "Silogismo Hipotético (doble) + Modus Ponens",
    "accionCorrecta": "VALIDO"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CASOS_LOGICA };
}
